"""
train_xgboost.py

Model Training, Walk-Forward Evaluation, and Strategy Backtesting.

Responsibilities:
- Load clean processed datasets generated by preprocess.py.
- Use TimeSeriesSplit for leak-free walk-forward cross-validation.
- Train XGBoost Classifier with active early stopping on validation folds.
- Compute ML Classification metrics (Accuracy, Precision, Recall, ROC-AUC).
- Backtest trading strategy with transaction cost friction (10 bps).
- Save trained model JSON artifacts and performance report.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import TimeSeriesSplit
from xgboost import XGBClassifier

import config

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger("train_xgboost")


def calculate_quant_metrics(returns: pd.Series, risk_free_rate: float = 0.05) -> Dict[str, float]:
    """
    Computes standard quantitative metrics from daily strategy returns.
    Assumes 252 trading days per year.
    """
    if len(returns) == 0 or returns.std() == 0:
        return {
            "Annualized_Return": 0.0,
            "Sharpe_Ratio": 0.0,
            "Max_Drawdown": 0.0,
            "Win_Rate": 0.0
        }

    equity_curve = (1 + returns).cumprod()
    
    # 1. Annualized Return (CAGR)
    n_days = len(returns)
    total_return = equity_curve.iloc[-1] - 1.0
    cagr = (1 + total_return) ** (252 / n_days) - 1.0

    # 2. Sharpe Ratio
    daily_rf = (1 + risk_free_rate) ** (1 / 252) - 1.0
    excess_returns = returns - daily_rf
    sharpe_ratio = np.sqrt(252) * (excess_returns.mean() / (returns.std() + 1e-8))

    # 3. Maximum Drawdown (Max DD)
    rolling_max = equity_curve.cummax()
    drawdown = (equity_curve - rolling_max) / rolling_max
    max_drawdown = float(drawdown.min())

    # 4. Win Rate
    win_rate = float((returns > 0).mean())

    return {
        "Annualized_Return": float(round(cagr, 4)),
        "Sharpe_Ratio": float(round(sharpe_ratio, 4)),
        "Max_Drawdown": float(round(max_drawdown, 4)),
        "Win_Rate": float(round(win_rate, 4))
    }


def backtest_signals(
    df: pd.DataFrame, 
    predictions: np.ndarray, 
    cost_bps: float = config.TRANSACTION_COST_BPS
) -> pd.DataFrame:
    """
    Simulates daily trading strategy using XGBoost signals.
    Applies transaction costs when position changes state.
    """
    bt_df = df.copy()
    
    # Position: 1 (Long) or 0 (Cash)
    bt_df["Signal"] = predictions
    
    # Market daily return
    bt_df["Market_Return"] = (bt_df["Close"] - bt_df["Close"].shift(1)) / bt_df["Close"].shift(1)
    
    # Shift position by 1 day to execute on close/next open (prevent same-bar execution bias)
    bt_df["Position"] = bt_df["Signal"].shift(1).fillna(0)
    
    # Detect trades (position change) to apply transaction costs
    bt_df["Trades"] = bt_df["Position"].diff().abs().fillna(0)
    
    # Strategy Return = Position * Market_Return - Transaction_Costs
    bt_df["Strategy_Return"] = (bt_df["Position"] * bt_df["Market_Return"]) - (bt_df["Trades"] * cost_bps)
    
    # Equity Curves
    bt_df["Market_Equity"] = (1 + bt_df["Market_Return"].fillna(0)).cumprod()
    bt_df["Strategy_Equity"] = (1 + bt_df["Strategy_Return"].fillna(0)).cumprod()

    return bt_df


def load_pooled_dataset(processed_dir: Path) -> pd.DataFrame:
    """
    Loads and concatenates every processed stock CSV into one chronologically
    sorted, multi-stock dataset. Each row keeps a 'StockFile' tag (derived from
    the source filename) so per-stock backtests can still be reconstructed
    from the pooled predictions later.
    """
    processed_files = sorted(processed_dir.glob("*.csv"))
    if not processed_files:
        raise FileNotFoundError(
            f"No processed CSV files found in {processed_dir}. Run preprocess.py first."
        )

    df_list = []
    for file_path in processed_files:
        df = pd.read_csv(file_path)
        df[config.DATE_COLUMN] = pd.to_datetime(df[config.DATE_COLUMN])
        df["StockFile"] = file_path.stem
        df_list.append(df)

    pooled = pd.concat(df_list, axis=0, ignore_index=True)
    pooled.sort_values(by=config.DATE_COLUMN, ascending=True, inplace=True, kind="mergesort")
    pooled.reset_index(drop=True, inplace=True)
    return pooled


def train_generalized_model(n_splits: int = 5) -> Dict[str, Any]:
    """
    Pools every processed stock CSV into a single unified dataset, runs
    leak-free walk-forward (TimeSeriesSplit) cross validation on the pooled,
    chronologically-sorted data, and trains ONE generalized XGBoost classifier
    across all stocks. Also backtests the resulting out-of-fold signals
    per-stock (to keep position/return math valid per instrument) and reports
    the average strategy vs buy-and-hold performance.
    """
    logger.info("Loading and pooling processed datasets...")
    pooled_df = load_pooled_dataset(config.PROCESSED_DATA_DIR)
    logger.info("Pooled dataset assembled: %d rows across %d stock file(s).",
                len(pooled_df), pooled_df["StockFile"].nunique())

    # Derive feature columns dynamically using config.EXCLUDE_COLUMNS.
    # StockFile is a training-time helper column only, never a model feature.
    exclude_set = set(config.EXCLUDE_COLUMNS) | {"StockFile"}
    feature_cols = [c for c in pooled_df.columns if c not in exclude_set]

    X = pooled_df[feature_cols].values
    y = pooled_df[config.TARGET_COLUMN].values

    tscv = TimeSeriesSplit(n_splits=n_splits)

    oof_predictions = np.zeros(len(pooled_df))
    oof_probabilities = np.zeros(len(pooled_df))
    oof_mask = np.zeros(len(pooled_df), dtype=bool)

    # Walk-forward cross validation over the pooled, chronologically-sorted data
    for fold, (train_idx, test_idx) in enumerate(tscv.split(X)):
        X_train, y_train = X[train_idx], y[train_idx]
        X_test, y_test = X[test_idx], y[test_idx]

        model = XGBClassifier(
            n_estimators=1000,
            max_depth=3,
            learning_rate=0.015,
            subsample=0.8,
            colsample_bytree=0.8,
            early_stopping_rounds=50,  # Active early stopping
            random_state=42,
            eval_metric="logloss"
        )

        model.fit(
            X_train, y_train,
            eval_set=[(X_test, y_test)],
            verbose=False
        )

        preds = model.predict(X_test)
        probs = model.predict_proba(X_test)[:, 1]

        oof_predictions[test_idx] = preds
        oof_probabilities[test_idx] = probs
        oof_mask[test_idx] = True

    # Out-of-sample evaluation (pooled, across all stocks)
    test_y = y[oof_mask]
    test_preds = oof_predictions[oof_mask]
    test_probs = oof_probabilities[oof_mask]
    test_df = pooled_df.iloc[oof_mask].copy().reset_index(drop=True)
    test_df["Signal"] = test_preds

    # 1. Classification Metrics
    acc = float(round(accuracy_score(test_y, test_preds), 4))
    prec = float(round(precision_score(test_y, test_preds, zero_division=0), 4))
    rec = float(round(recall_score(test_y, test_preds, zero_division=0), 4))
    auc = float(round(roc_auc_score(test_y, test_probs), 4))

    clf_metrics = {
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "ROC_AUC": auc
    }

    # 2. Backtest Financial Metrics, computed per stock (so position/equity math
    # stays valid for a single instrument) then averaged across stocks.
    strat_runs, bnh_runs = [], []
    for _, group in test_df.groupby("StockFile"):
        group = group.sort_values(by=config.DATE_COLUMN)
        bt_results = backtest_signals(group, group["Signal"].values)
        strat_runs.append(calculate_quant_metrics(bt_results["Strategy_Return"].dropna()))
        bnh_runs.append(calculate_quant_metrics(bt_results["Market_Return"].dropna()))

    def _average_metrics(runs: List[Dict[str, float]]) -> Dict[str, float]:
        if not runs:
            return {}
        keys = runs[0].keys()
        return {k: float(round(np.mean([r[k] for r in runs]), 4)) for k in keys}

    strat_metrics = _average_metrics(strat_runs)
    bnh_metrics = _average_metrics(bnh_runs)

    # Retrain final generalized model on the FULL pooled dataset for export
    final_model = XGBClassifier(
        n_estimators=200,
        max_depth=3,
        learning_rate=0.015,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    )
    final_model.fit(X, y)

    # Save the single generalized model artifact
    model_path = config.MODELS_DIR / config.GENERALIZED_MODEL_NAME
    final_model.save_model(str(model_path))
    logger.info("Generalized model saved to %s", model_path)

    summary = {
        "model": config.GENERALIZED_MODEL_NAME,
        "stocks_used": sorted(pooled_df["StockFile"].unique().tolist()),
        "features_used": feature_cols,
        "out_of_sample_rows": int(len(test_df)),
        "classification_metrics": clf_metrics,
        "xgboost_metrics": strat_metrics,
        "buy_and_hold_metrics": bnh_metrics
    }

    return summary


def train_all_stocks() -> List[Dict[str, Any]]:
    """Trains the single pooled, generalized model and saves a report."""
    try:
        summary = train_generalized_model()
    except FileNotFoundError as e:
        logger.error(str(e))
        return []
    except Exception as e:
        logger.error("Error training generalized model: %s", str(e), exc_info=True)
        return []

    all_summaries = [summary]

    report_path = config.REPORTS_DIR / "xgboost_baseline_report.json"
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(all_summaries, f, indent=4)

    logger.info("Training complete. Baseline performance report saved to %s", report_path)
    return all_summaries


if __name__ == "__main__":
    logger.info("Initializing XGBoost Training Pipeline...")
    train_all_stocks()
    logger.info("Execution complete.")